[package]
name = "rust-boilerplate"
version = "0.1.0"
authors = ["Chris <chris@christianarndt.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.13"
simplelog = "0.9.0"
serde = "1.0.119"
ron = "0.6.4"